version: '3.1'
services:
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - webnet
networks:
  webnet:
volumes:
  dbdata:
