version: '3.1'
services:
  web:
    # replace username/repo:tag with your name and image details
    image: oshopaspnetcore
    entrypoint:
      - dotnet
      - OnlineShopV1.dll
      #- --ef-migrate
    environment:
      - ConnectionStrings:DefaultConnection=server=mysqldb;username=root;password=example;database=o_shop_dnc_1;CharSet=utf8mb4;
    ports:
      - "4000:80"
    networks:
      - webnet
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - webnet
networks:
  webnet:
volumes:
  dbdata:
